// Generated by jextract

package org.jjazz.fluidsynthjava.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef int (*fluid_sfloader_callback_read_t)(void *, fluid_long_long_t, void *)
 * }
 */
public class fluid_sfloader_callback_read_t {

    fluid_sfloader_callback_read_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment buf, long count, MemorySegment handle);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        fluidsynth_h.C_INT,
        fluidsynth_h.C_POINTER,
        fluidsynth_h.C_LONG_LONG,
        fluidsynth_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = fluidsynth_h.upcallHandle(fluid_sfloader_callback_read_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(fluid_sfloader_callback_read_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment buf, long count, MemorySegment handle) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, buf, count, handle);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

